### ISSUE TITLE
Consolidate promises in _find() method.

### ISSUE THREAD

**Issue by DaddyWarbucks** [bwgjoseph/feathers-ottoman#1]
I think you could combine the query and count promises into a `Promsie.all` in the `_find` method for better performance.
See: https://github.com/bwgjoseph/feathers-ottoman/blob/c3468c82b0066094be6e3761115f6dbeb141a7cb/src/index.ts#L268

Maybe something like this
```js
const [result, total] = await Promsie.all([
  this.Model.find(cQuery, cOptions),
  Object.keys(paginate).length > 0 ? this.Model.count(cQuery) : null
]);

if (total) {
  return {
    total,
    limit: filters.$limit,
    skip: filters.$skip || 0,
    data: result.rows
  };
}

return result.rows && result.rows.length > 0 ? result.rows : [];

```

**Comment by bwgjoseph** [comment]
Good suggestion! Thank you.

Will make this change soon
